---
title: "Homework 3"
output: github_document
---

```{r, message = FALSE, echo = FALSE}
library(tidyverse)
library(p8105.datasets)
library(ggridges)
library(patchwork)



knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1

## importing data and cleaning up
```{r}
data("ny_noaa")

ny_noaa %>% 
  count(snow) %>%
  arrange(desc(n))

ny_noaa = 
  ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin))
```

```{r}
ny_noaa %>% 
  group_by(id, year, month) %>% 
  filter(month %in% c(1, 7)) %>% 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE, color = id)) %>% 
  ggplot(aes(x = year, y = mean_tmax, group = id)) + geom_point() + geom_path() +
  facet_grid(~month) +
  labs(title = "Mean monthly temperature for each station across years for January and July")
```

```{r}
hex = 
  ny_noaa %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_hex()

ridge = 
  ny_noaa %>% 
  filter(snow < 100, snow > 0) %>%
  ggplot(aes(x = snow, y = as.factor(year))) + 
  geom_density_ridges()

hex + ridge
```

# Problem 2

## importing data and cleaning up
```{r}
participant = read_csv("data/participant.csv", skip = 4) %>% 
  janitor::clean_names() %>% 
  mutate(
    sex = case_match(
      sex,
      1 ~ "male",
      2 ~ "female")
  )

accelerometer = read_csv("data/accelerometer.csv",) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    cols = min1:min1440,
    names_to = "time_elasped",
    names_transform = list(time_elasped = as.integer),
    values_to = "mims",
    names_prefix = "min"
  )

study = left_join(participant, accelerometer, by = "seqn") %>% 
  mutate(
    education = as.factor(education)
    )%>% 
  filter(age >= 21) %>% 
  drop_na(education)
```


```{r sex }
participant_sex = participant %>%
  drop_na(education) %>% 
  group_by(sex, education) %>% 
  summarise(total_count = n(), .groups = 'drop') %>% 
  as.data.frame()

participant %>% drop_na(education) %>% 
  ggplot(aes(x= age, y = education)) +
  geom_point(aes(color = sex )) + 
  labs(title = "Age distributions for men and women in each education category.")
```

## Problem 3
```{r}
Jan2020 = read_csv("data/citibike/Jan 2020 Citi.csv.zip") %>% 
  janitor::clean_names() %>% 
  mutate(
    date = "Jan2020"
  )

Jan2024 = read_csv("data/citibike/Jan 2024 Citi.csv.zip") %>% 
  janitor::clean_names() %>% 
  mutate(
    date = "Jan2024"
  )

July2020 = read_csv("data/citibike/July 2020 Citi.csv.zip") %>% 
  janitor::clean_names() %>% 
  mutate(
    date = "July2020"
  )

July2024 = read_csv("data/citibike/July 2024 Citi.csv.zip") %>% 
  janitor::clean_names() %>% 
  mutate(
    date = "July2024"
  )


```

